# Generated by Django 6.0.4 on 2026-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='Expense', max_length=200),
        ),
    ]
